# Exported from Render on 2025-04-14T18:09:30Z
services:
- type: web
  name: Node-RED-Render
  runtime: docker
  repo: https://github.com/cgjgh/Node-RED-Render
  plan: free
  envVars:
  - key: TZ
    value: America/Chicago
  - key: NODE_RED_ADMIN_USER
    sync: false
  - key: NODE_RED_ADMIN_PASS
    sync: false
  - key: NODE_RED_CREDENTIAL_SECRET
    sync: false
  - key: GIT_USER_NAME
    sync: false
  - key: GIT_USER_EMAIL
    sync: false
  - key: GITHUB_TOKEN
    sync: false
  - key: REPO_FULL_NAME
    sync: false
  - key: CLOUDFLARED_TOKEN
    sync: false
  - key: CLOUDFLARE_URL
    sync: false
  region: ohio
  healthCheckPath: /
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
